apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vote-ui
  template:
    metadata:
      labels:
        app: vote-ui
    spec:
      containers:
      - image: docker.io/eeganlf/vote:de4657461f0eba24159840439e36ec4649551585
        name: vote-ui
        ports:
        - containerPort: 80
